import pandas as pd


def read_percolator_psms(filename):
    """Read a tab-limited file containing PSMs
        as generated by Percolator."""
    with open(filename) as f:
        columns = f.readline().split()
        content = []
        for line in f:
            split = line.split()
            psm = split[: len(columns) - 1]
            psm.append(split[len(columns) - 1:])
            content.append(psm)

    df = pd.DataFrame(content, columns=columns)
    # df[["score", "q-value"]] = df[["score", "q-value"]].apply(pd.to_numeric)

    return df
